# List of constants

# User apps
MAX_LEN_EMAIL = 254
MAX_LEN_USER_FIELD = 150
ITEM_PER_PAGE_ADMIN = 20

# Recipes apps
MAX_LEN_RECIPES = 200
MIN_INGREDIENT_AMOUNT = 1
MIN_COOKING_TIME = 1
LEN_HEX_CODE = 7
